# Generated by Django 6.0.3 on 2026-03-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
