# Generated by Django 6.0 on 2026-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
